### ISSUE TITLE
First Tab Blank

### ISSUE THREAD

**Issue by max221** [ericfinn/TodaysPages#8]
It would be great if the initial open tab was changed to the first bookmark of the day; in other words, I have nine urls set to open every day, and I end up with ten tabs--the first blank. Thanks!

**Comment by ericfinn** [comment]
Hey there, thanks for the request!
The way I'm thinking of doing this is making it so that it only overwrites the current tab if it's a blank one (about:blank or about:newtab). Would that work for you?
Otherwise, I don't think I'd get around to this until I implement settings, so that blowing away the current tab(s) is an option that can be toggled.

**Comment by ericfinn** [comment]
0.3.0 is live with this change.
